spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/sterling_platform}
    username: ${DATABASE_USERNAME:sterling_user}
    password: ${DATABASE_PASSWORD:sterling_password}
  
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    com.sterling.entitlement: INFO
    org.springframework.cache: WARN
    org.hibernate.SQL: WARN
    root: WARN

# Production specific settings
entitlement:
  performance:
    max-computation-time-ms: 5000  # Strict performance requirements
  audit:
    retention-days: 30  # Full retention for production
