spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/ccaas_platform}
    username: ${DATABASE_USERNAME:ccaas_user}
    password: ${DATABASE_PASSWORD:ccaas_password}
  
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    com.ccaas.entitlement: INFO
    org.springframework.cache: WARN
    org.hibernate.SQL: WARN
    root: WARN

# Production specific settings
entitlement:
  performance:
    max-computation-time-ms: 5000  # Strict performance requirements
  audit:
    retention-days: 30  # Full retention for production
