spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/ccaas_platform
    username: ccaas_user
    password: ccaas_password
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.ccaas.entitlement: DEBUG
    org.springframework.cache: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Development specific settings
entitlement:
  performance:
    max-computation-time-ms: 10000  # More lenient for development
  audit:
    retention-days: 7  # Shorter retention for development
